version: '3'
services:
  brightspot:
    build: .
    hostname: training.localhost
    ports:
      - 80:80
      - 5005:5005
    volumes:
      - .:/code
      - mysql-data:/var/lib/mysql
      - solr-data:/servers/solr/solr/collection1/data
      - storage-data:/servers/brightspot/www/storage
    environment:
      - ROOT_WAR=/code/site/build/libs/training-site-1.0.0-SNAPSHOT.war
volumes:
  mysql-data:
  solr-data:
  storage-data:
